### ISSUE TITLE
Version for torch,torch_geometric,pyscipopt,ecole

### ISSUE THREAD

**Issue by jp18813100494** [lascavana/rl2branch#1]
Can you show the version for torch,torch_geometric,pyscipopt,ecole,especially for torch_geometric.It will be better if you can show how to install these library.I meet lost of problem for installing these libraries!

**Comment by jp18813100494** [comment]
![微信图片_20221004231013](https://user-images.githubusercontent.com/26135273/193856995-8b4b9f1a-6080-4bfe-88a1-8662a231e2b4.jpg)
This is the problem when I deal with the dataset with torch_geometric.data.Dataloader.

**Comment by lascavana** [comment]
These are the versions I used
```
torch==1.9.0
torchvision==0.10.0
torch_scatter=2.0.7
torch_sparse==0.6.10
torch_geometric==1.7.2
```

**Comment by jp18813100494** [comment]
> These are the versions I used
> 
> ```
> torch==1.9.0
> torchvision==0.10.0
> torch_scatter=2.0.7
> torch_sparse==0.6.10
> torch_geometric==1.7.2
> ```

Thanks a lot ! The matter is the version for torch_geometric! Another problem: can your tell me the version for ecole! I do not how to install ecole tree_mdp !I guess you make several modifications for ecole in ecole_tree_mdp!

**Comment by lascavana** [comment]
[This](https://github.com/dchetelat/ecole-tree-mdp) is the repo we used. What we did to install it is the following. First you compile it and create a wheel:
```
git clone git@github.com:dchetelat/ecole-tree-mdp.git
cd ecole-tree-mdp
cmake -B build/ -D CMAKE_BUILD_TYPE=Release
cmake --build build/ --parallel
python build/python/setup.py bdist_wheel --dist-dir $HOME/wheels
```
Then you are ready to install:
```
python -m pip install --no-index --find-links=$HOME/wheels ecole
```
I will soon improve the installation instructions with all this information. Thanks for pointing it out!

**Comment by jp18813100494** [comment]
Thanks for your reply! I meet lots of problem when I compile it following your steps. I meet the cmake warning when execute 
`cmake -B build/ -D CMAKE_BUILD_TYPE=Release`                 
But I suppose the warning is not important, I ignore this tiny problem! But when I execute:                          
`python build/python/setup.py bdist_wheel --dist-dir $HOME/wheels`
I found there is no setup.py in build/python, I move the setup.pt in the root dir to build/python, but it shows 
 **No such file or directory: '/home/jiangp/Package/ecole-tree-mdp/build/python/VERSION'**
maybe it loses some dependency package? It is a big problem for me! Can you give me more comprehensive details for the installation?

**Comment by xiaofeishu141220** [comment]
When I follow the above command to compile, it reports this error：

make[2]: *** [CMakeFiles/xtensor-python-populate.dir/build.make:92: xtensor-python-populate-prefix/src/xtensor-python-populate-stamp/xtensor-python-populate-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/xtensor-python-populate.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

CMake Error at /usr/share/cmake-3.16/Modules/FetchContent.cmake:915 (message):
  Build step for xtensor-python failed: 2
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FetchContent.cmake:1006 (__FetchContent_directPopulate)
  cmake/Dependencies.cmake:79 (FetchContent_Populate)
  python/CMakeLists.txt:13 (find_or_download_package)


-- Configuring incomplete, errors occurred!

**Comment by MoonieC** [comment]
@jp18813100494 Have you solved this problem? I meet the same problem

**Comment by xuxiaoxia8385** [comment]
@lascavana  @jp18813100494 @MoonieC 
Hi, have you addressed the problem for finding the _setup.py_ in build/python/? 
I have turned my cmake from version 3.28 into version 3.22, and then all the warnings are fixed during the whole process. 
However, I cannot find the setup.py file in build/python/ to execute 

> python build/python/setup.py bdist_wheel --dist-dir $HOME/wheels

Any helps would be really appreciated!

**Comment by lascavana** [comment]
Dear all, I have updated the installation instructions to be more detailed. Hopefully this solves all your issues. Thanks for the wait.
