### ISSUE TITLE
model.as_pyscipopt() error!

### ISSUE THREAD

**Issue by yigeNNU** [lascavana/rl2branch#5]
scip_model = env.model.as_pyscipopt()
File "src/pyscipopt/scip.pyx", line 992, in pyscipopt.scip.Model.from_ptr
TypeError: an integer is required

I have printed the 'env.model', follows:
<class 'ecole.core.scip.Model'>
But, it still has the above bug. Please help me, thanks!

**Comment by lascavana** [comment]
I believe this is a duplicate of the other open issue so I am closing it.
