### ISSUE TITLE
About the usage of ecole

### ISSUE THREAD

**Issue by MoonieC** [lascavana/rl2branch#6]
![image](https://github.com/lascavana/rl2branch/assets/59831989/12e6a353-647d-4b34-80c0-effe5628b1b3)
Do you have any idea how to solve this problem? it seems the ecole.observation is missing a focusnode attribute, and I have tried ecole 8.0.1 and ecole 7.0.3, they still present the same question.

**Comment by asteriwalker** [comment]
Have you solved this problem? I have encountered the same issue.

**Comment by lascavana** [comment]
It seems you do not have the correct version of Ecole. You need to install [this](https://github.com/lascavana/ecole) special version. I have updated the installation instructions with more details.
