### ISSUE TITLE
About ecole version or AttributeError: module 'ecole.observation' has no attribute 'FocusNode'

### ISSUE THREAD

**Issue by hlq-git** [lascavana/rl2branch#7]
I'm using ecole 7.0.3 and I get an error when running python 05_train_rl.py mknapsack mdp -g 0
![image](https://github.com/lascavana/rl2branch/assets/82200024/e6bceb0b-cb8d-4630-b6d8-e665e271b208)
![image](https://github.com/lascavana/rl2branch/assets/82200024/09372b53-b91b-4887-85bf-88d2977c99a7)
AttributeError: module 'ecole.observation' has no attribute 'FocusNode'
Can I ask how the FocusNode property needs to be added, or how the version of ecole needs to be changed? Can you provide me with your ecole installation method, thanks!

**Comment by zxl1212** [comment]
Have you solved this? I have the same question.

**Comment by lascavana** [comment]
You need a special version of [Ecole](https://github.com/lascavana/ecole) that has this observation. I have just updated the installation instructions with more details.
